CREATE TABLE `trial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `remark` VARCHAR(255) DEFAULT NULL,
  `create_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `update_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
)
